name: Trigger reindexing
on:
  workflow_dispatch:
  repository_dispatch:
    type:
      resource-published
      resource-unpublished

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch reindex event
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.SEARCH_INDEX_ACCESS_TOKEN }}
          repository: headwire-edge-delivery/search-index
          event-type: reindex